### ISSUE TITLE
MP3: Movement in reverse breaks at branching points

### ISSUE THREAD

**Issue by PartyPlanner64** [PartyPlanner64/PartyPlanner64#21]
Moving in reverse requires building out different space events that trigger when the player is moving backwards. Without these, memory values for the next chain / space become corrupt and the player path becomes unpredicable, leaning to crashing / hanging.

**Comment by PartyPlanner64** [comment]
I addressed this today.

**Comment by Yoshiman222** [comment]
It crashed when I made a pathway not long ago and a CPU went into it in reverse. I also went into it but a different way so that it only provided me with 2 options, the path I came from and forwards the opposite direction, however, after choosing to go backwards, I was presented with another choice of options, one where I could go backwards in the other direction and the direction I originally came from. (To explain how the path works, 2 chains lead into it while 2 lead out from it)

**Comment by Yoshiman222** [comment]
Also the movement was also caused by Bowser's Reverse curse too if that means anything. Also I believe the CPU could make it to start if that also means anything though I doubt it since start normally starts off outside the board regardless right?
