### ISSUE TITLE
Event spaces disappearing after patching ROM

### ISSUE THREAD

**Issue by StalfosKing** [PartyPlanner64/PartyPlanner64#28]
I placed an event space next to Boo and then patched the ROM. After I loaded up this ROM in PP64, I found that the event that was attached to the space was gone. I did use the space that is used for junctions (not sure what to call this space). This combined with other issues is making my board nearly impossible to create properly.

**Comment by PartyPlanner64** [comment]
It is a bug that sometimes PP64 is not able to parse events that it wrote when loading a ROM back in again. It has been lower priority because I don't think it is common that a patched ROM is opened again in PP64.

I'm not sure why this is causing you so much trouble? You can always load a fresh ROM and re-apply your board while making changes. If the board is really large and the browser is not willing to save it to local storage, you should use the "Export Board" option to save the board file, and then import it again when you use PP64 next time. There are no issues like this with reading board files, so all the events will be fine through an export/import.

**Comment by StalfosKing** [comment]
Thanks for the quick response. I only posted this issue because I assumed that because PP64 was not showing these events, they were not in game either. This was my fault, as I should have tested it before so quickly reporting the bug. Thanks again for the quick response and thank you for working so hard on this project!

**Comment by PartyPlanner64** [comment]
Closing this issue, as the board file is now stored in the ROM, which allows for the custom boards to be retrieved completely.
