### ISSUE TITLE
MP1 crashes in pipe with corrupt board select image

### ISSUE THREAD

**Issue by trhodges** [PartyPlanner64/PartyPlanner64#30]
Everything checked out supposedly when creating it.

**Comment by trhodges** [comment]
[Harambe Island.zip](https://github.com/PartyPlanner64/PartyPlanner64/files/578674/Harambe.Island.zip)

That's my board if that helps

**Comment by PartyPlanner64** [comment]
It doesn't crash for me, but I do see that the board select image is corrupted for some reason. It is very possible that other emulators might crash because of this, so I will need to look into what is wrong with that image.

In the meantime I would suggest changing the board select image and seeing if that resolves it.

**Comment by PartyPlanner64** [comment]
Well I use nemu mostly because it has a debugger, but I have also used mupen64plus with some success. Neither of those are terribly mainstream so I need to do more testing in Project64 (which, based on what I hear, works best with v2.3 rather than 1.6).

**Comment by trhodges** [comment]
Ok cool, thanks!

**Comment by PartyPlanner64** [comment]
I fixed the corruption of the board select images in MP1 in commit 1e86be9. I can't say 100% that this fixed a crash but it is the only clue I had to go on with this board.

**Comment by trhodges** [comment]
Ok cool I'll give it a try. Thanks!
