### ISSUE TITLE
ROM list does not refresh after overwriting

### ISSUE THREAD

**Issue by TheNintendoReject** [PartyPlanner64/PartyPlanner64#34]
Here is what happens. also say hi to camtro for me and Dega too
![2016-11-10_23-18-49](https://cloud.githubusercontent.com/assets/23401536/20216282/b3f52ca8-a7e7-11e6-9b97-cdaa5955c054.gif)
Edit: Yes i did take off the NPCs from the player path

**Comment by PartyPlanner64** [comment]
Thanks for mentioning, fixed in commit 28040be. The board was getting overwritten, but I was not refreshing the board list. Now it should refresh after overwriting.

If you view the ROM board after there may be some strange differences. These are mostly still bugs with PP64 but they are lower priority since what really matters is how the actual game plays.
