### ISSUE TITLE
Large screen background removed when overwriting ? ( MP2 )

### ISSUE THREAD

**Issue by Lefonna** [PartyPlanner64/PartyPlanner64#35]
#I feel like I did everything I should but for some reason, the large screen background is gone after overwriting the western land map. I made sure it was 320 x 240 but it still doesn't work. I can't launch the rom because of that.

I'm using Project 64 BTW. Here are the files if it can helps :  

http://www.mediafire.com/file/1sxj627r6w8s751/mp2-files.zip
http://www.mediafire.com/file/8u9vwf0dg11g15h/Mad_Monster_Mansion%281%29.json

I tried changing the large screen background and the problem is still here.

Thank you in advance for looking into it.

**Comment by PartyPlanner64** [comment]
Thanks, I've made it so the large scene background is read for MP2/3 in commit ba17e4ec, so you should see the change soon.

But this was just an editor bug that it wasn't reading the background, it should have been writing it fine. So the problem with the ROM is probably due to an emulator issue, most likely you need to set it to use 8MB RDRAM, or try another emulator.

**Comment by Lefonna** [comment]
Thanks, that fixed it. Time for beta testing
