### ISSUE TITLE
Bug - No Duel on Happening Space

### ISSUE THREAD

**Issue by SuperZambezi** [PartyPlanner64/PartyPlanner64#51]
We were playing a 50 turn game on Paradise Isles (woop woop!) and we were on the last four turns. Yoshi landed on Waluigi's space which should have triggered a duel but instead the turn ended. That space was a Happening space.

Here's a video that shows what happened:

https://www.youtube.com/watch?v=0wjAXfjkaH0

**Comment by PartyPlanner64** [comment]
Thanks for the bug report.

I'm wondering how this works for happening spaces in normal games, since they usually also cause something happen. Does the happening space event occur, and then a duel?

My guess at the moment is that happening space events might be responsible for telling the game engine to proceed with a duel after they finish. But since PP64 doesn't have any events at all on these spaces, this wouldn't happen.

**Comment by PartyPlanner64** [comment]
gamemasterplc sent me a patch to fix this issue. Duels should be working on happening spaces, I haven't noticed any side effects yet.
