### ISSUE TITLE
Crashing when landing on specific space (MP3)

### ISSUE THREAD

**Issue by StalfosKing** [PartyPlanner64/PartyPlanner64#54]
For reasons unknown, on my current WIP board, the game crashes when I land on a single specific space. Not sure if there are others of its kind or not, I have not tested thoroughly enough. The interesting thing is that it crashes the NEXT turn, right after the player who landed on the space rolls the dice block and just before they move off of the space. I tried erasing and replacing the space, even changing the type of space, but the issue persists. I have a hunch that it may be another stability issue affected by the number of total spaces, but I have not come to a conclusion yet. I will attach the board once the contest results are in.

**Comment by StalfosKing** [comment]
Is there any way to send you the .json privately?

**Comment by StalfosKing** [comment]
Found that the only workaround seems to be to remove the space entirely. I worry that there are others of its kind.

**Comment by StalfosKing** [comment]
Talked with other members on the Mario Party Legacy forums, they are having very similar issues, though not necessarily the exact same; they mention frequent crashing but not in the same ways as I have seen.

**Comment by PartyPlanner64** [comment]
I'm speculating that there is instability when the space count exceeds 128 spaces. For now I have implemented a warning that will let you know when you've exceeded that amount.

**Comment by PartyPlanner64** [comment]
A slight elaboration:

The original boards do actually have more than 128 spaces, but they don't have stability issues.

Each space is associated with an "index" and you can see these by enabling debug features. The original game boards seem to make sure that the player can never land on a space with index >= 128 (0x80). The spaces that exceed that index seem to be invisible spaces exclusively. Related to the other issue, the banks are also (_usually_) not placed on spaces with such high indices.

If you were to ensure that the indices of the solid spaces were below 0x80, you'd likely be stable at high space counts if this theory is correct. Unfortunately, PP64 manages the indices for you by just assigning them incrementally as you add spaces, so to manipulate them you'd have to be very careful in adding all invisible spaces last. Or you could delete all invisible spaces and re-add them; deleting spaces shifts the indices of the remaining spaces downward to fill the gap.

I may look into automatically re-assigning the space indices optimally to avoid this if it turns out this is what is required.
