### ISSUE TITLE
Support custom music

### ISSUE THREAD

**Issue by SomethingRando123** [PartyPlanner64/PartyPlanner64#96]
It would be splendid if we could add our own music to the board. I understand this could mess with console compatibility, but what if you compressed the music to the point a n64 could handle?

**Comment by RainbowTHOfficial** [comment]
You'd have to know how to compress music enough so the N64 could handle it, and then find a way to do that with any music track, plus the formula has to work with all three N64 Mario Parties. It's indeed possible, but only the gods of N64 ROM Hacking know how to do it as far as I'm aware.

**Comment by Shadic64SSF** [comment]
Oh boy, do I have news for you guys. Custom Music is possible, though limited. By using a tool called N64 Midi Tool we are able to replace to songs of the game with our own. The song must be a .mid file and you're going to have to edit it too so that the instruments display correctly! Examples of Custom Music can be found on my boards, Knuckles Park & Mario's Midnight Pizza. If you're looking for exact details for how to do this, ask away!

**Comment by SomethingRando123** [comment]
That is really cool to know. Thanks!

**Comment by SomethingRando123** [comment]
Also, what do you mean by Instruments display correctly?

**Comment by PartyPlanner64** [comment]
The latest release has support for attaching a midi music file to boards for use as the background music. This requires midi editing knowledge, to create midis that are compatible with a soundbank in the game. I will leave this github issue open until we have a tutorial for learning how to do this.

**Comment by PartyPlanner64** [comment]
Here is a tutorial about custom music by @Shadic64SSF.

https://docs.google.com/document/d/1Yn0PqKTswf3UQFEHV4AgX6j5VlrVLfp5Y1qj543Sgfk/edit

I am closing this github now as the custom music functionality is now released.
